### ISSUE TITLE
Can't create short URL of image if image is also a link

### ISSUE THREAD

**Issue by Xebtria** [ettoolong/GooglUrl#1]
Title.

Extension works fine if object is a just an image
Extension works also fine if object is just a picture

however, if the object is an image and a link at the same time, it only shortens the url of the link. 

would it be possible to give an option in that case, whether I want to shorten the URL of the image or the link?

**Comment by ettoolong** [comment]
Fixed in v0.0.8.

**Comment by Xebtria** [comment]
awesome, thanks a lot!
